<a href="https://colab.research.google.com/github/kkewat/Placement_Prediction/blob/main/Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# **Import Cleaned Dataset**

In [81]:
data = pd.read_excel('/content/drive/MyDrive/Data/Train_Cleaned.xlsx')
data.head()

CGPA  Speaking Skills  ML Knowledge  Placement Status
0   6.7                2             5                 1
1   8.2                3             2                 0
2   6.5                4             3                 0
3   8.7                2             5                 0
4   9.1                3             5                 1

In [82]:
# Seperating Dependent and Independent variable
x = data.drop(['Placement Status'], axis = 1)
y = data['Placement Status']
x.shape, y.shape

((4894, 3), (4894,))

In [83]:
x.head()

CGPA  Speaking Skills  ML Knowledge
0   6.7                2             5
1   8.2                3             2
2   6.5                4             3
3   8.7                2             5
4   9.1                3             5

# ***Implementing Train Test split***

In [84]:
# Importing the train test split function
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x,y, random_state = 42, stratify=y)

# ***Implementing The Model***

In [85]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [86]:
rf_classifier = RandomForestClassifier(class_weight='balanced' ,n_estimators=100, random_state=42)

In [87]:
rf_classifier.fit(train_x, train_y)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [88]:
y_pred = rf_classifier.predict(test_x)

In [89]:
accuracy = accuracy_score(test_y, y_pred)
conf_matrix = confusion_matrix(test_y, y_pred)
class_report = classification_report(test_y, y_pred)

In [90]:
print(f'Accuracy: {accuracy:.2f}')
print(f'Confusion Matrix:\n{conf_matrix}')
print(f'Classification Report:\n{class_report}')

Accuracy: 0.41
Confusion Matrix:
[[ 58  55  70]
 [ 30  25  37]
 [278 253 418]]
Classification Report:
              precision    recall  f1-score   support

           0       0.16      0.32      0.21       183
           1       0.08      0.27      0.12        92
           2       0.80      0.44      0.57       949

    accuracy                           0.41      1224
   macro avg       0.34      0.34      0.30      1224
weighted avg       0.65      0.41      0.48      1224



** We will use our test data**

In [91]:
test_data = pd.read_excel('/content/drive/MyDrive/Data/Test_Cleaned.xlsx')

In [92]:
test_data.shape

(3795, 4)

In [93]:
data_x = test_data.drop(['Placement Status'], axis = 1)
data_y = test_data['Placement Status']

In [94]:
data_x.shape, data_y.shape

((3795, 3), (3795,))

In [95]:
output = rf_classifier.predict(data_x)

In [96]:
output.shape, data_x.shape

((3795,), (3795, 3))

In [97]:
output = pd.DataFrame(output)

In [98]:
result_data = pd.read_excel('/content/drive/MyDrive/Data/05 Input Data/Prediction of Placement Status Data/02 Test Data.xlsx')

In [99]:
result_data['Placement Status'] = output
result_data['Placement Status'] = result_data['Placement Status'].map({1:'Placed',0:'Not placed',2:'unknown'})

In [100]:
result_data.to_excel("/content/Scaled_Output.xlsx")

# **Export model**

In [101]:
import pickle

In [102]:
pickle.dump(rf_classifier,open('ml_model.pkl','wb'))